---
author_info:
  name: Libre Embedded
  email: vaughn@libre-embedded.com
  username: libre-embedded

# Use the same versions and systems that vmklib uses.
versions: ["3.13", "3.14"]
systems:
  - macos-latest
  - windows-latest
